### ISSUE TITLE
Build: Check the top-level render call using <head>

### ISSUE THREAD

**Issue by pamelahicks** [nozzle/react-static#430] opened 2018-03-05 17:59 UTC
The logging output on build is giving me:

`=> Exporting Routes...
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the top-level render call using <head>. See https://fb.me/react-warning-keys for more information.
    in link
    in HeadWithMeta
    in html
    in HtmlWithMeta
    in CustomHtml
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the top-level render call using <body>. See https://fb.me/react-warning-keys for more information.
    in script
    in BodyWithMeta
    in html
    in HtmlWithMeta
    in CustomHtml`

I am building a fresh install of styled components template, CLI v5.3.4.

**Comment by tannerlinsley** [comment] 2018-03-05 19:27
This is fixed in the beta that is currently out :) Thanks!

**Closed** 2018-03-05 19:27 UTC

**Comment by captainkovalsky** [comment] 2020-03-06 10:16
btw, what's the root cause?

**Comment by SleeplessByte** [comment] 2020-03-07 17:01
The root cause was that react-static was rendering an _array_ programmatically (for example `[1, 2, 3].map(() => <SomeComponent />)`), but forgot to include the `key=` property. The link in the original error message explains what this property does and why it's important.
