### ISSUE TITLE
Text not UTF-8 on server

### ISSUE THREAD

**Issue by AntoineGrandchamp** [nozzle/react-static#512] opened 2018-03-22 23:22 UTC
I have a issue with special characters once they are on my server. `é` are shown as `Ã©`. When I test my website with `yarn serve`, everything is fine. But once I transfer the folder `dist` on my server, I get these error. Is anyone else experiencing this issue ?

**Comment by denis-sokolov** [comment] 2018-03-27 08:56
I’m sorry, this does not seem to be a clearly described issue. Given your description, it is tricky to figure out what went wrong. If you suspect a bug in react-static build steps, please describe the way to reproduce it more clearly.

As a sidenote, I personally stay away from using non-ASCII names in development filenames. Hell, Atom has [an open bug](https://github.com/atom/atom/issues/1890) with them since 2014.

**Comment by denis-sokolov** [comment] 2018-03-27 08:58
And in case you are talking the contents of the file and not the filenames, then even more likely is that the content itself is fine, but the way you display it is not. Do you have a `<meta charset="utf-8">` in your resulting HTML?

**Comment by tannerlinsley** [comment] 2018-03-28 18:06
Yep, currently react-static requires UTF-8. This is more than doable in most circumstances. Closing for now, but feel free to reopen if you discover more details.

**Closed by tannerlinsley** 2018-03-28 18:06 UTC

**Comment by AntoineGrandchamp** [comment] 2018-03-28 19:10
I actually have `<meta charset="utf-8">` in my resulting HTML. The special characters rendering incorrectly comes from a .js file in the template folder. I managed to fix the problem by enconding the .js file with `utf-8 with bom`.
