### ISSUE TITLE
Warning and blank page when using withRouteData on homepage in 5.7.6

### ISSUE THREAD

**Issue by benedfit** [nozzle/react-static#567] opened 2018-04-16 19:58 UTC
I upgrade to 5.7.6 and when the app is hydrated in production I am warned about using withRouteData on the homepage. This results in the page being rendered as a blank page. Loading a child page, and then navigating back to the homepage works as expected, but refreshing the homepage produces the error again

**Comment by tannerlinsley** [comment] 2018-04-16 23:38
Please post your config or a link to your repo

**Comment by benedfit** [comment] 2018-04-17 08:55
https://github.com/avaclancheuk/destiny-clan-warfare

I have since downgraded back to `5.7.1`

**Comment by stilva** [comment] 2018-04-18 19:19
Reproduced the above based on `examples/basic` here: 1a22b4a, then run `npm run build && npm run serve`

When hydrating, [`window.__routeInfo.path === path`](https://github.com/nozzle/react-static/blob/master/src/client/components/RouteData.js#L74) fails because`window.__routeInfo.path === "/"` while `path === ""`

I'm not familiar enough with this project, so I'm not sure when `cleanPath` returning a falsy value is useful, but 742fa2a seems to fix this issue.

**Comment by stilva** [comment] 2018-04-20 20:57
@benedfit `v5.8.1` fixed this issue for me. Thanks for the fix @tannerlinsley! 🎉

**Comment by benedfit** [comment] 2018-04-20 21:49
I’ll try upgrading again and let you know how I get on

**Comment by tannerlinsley** [comment] 2018-04-24 04:58
Should be fixed in latest version

**Closed by tannerlinsley** 2018-04-24 04:58 UTC

**Comment by efarem** [comment] 2018-05-04 12:14
I'm seeing this error when serving prod bundles on version `5.9.1`. To reproduce just hit a route thats using the `withRouteData` HOC with `index.html` on the end.

Repro steps:

- `react-static create` (use basic)
- `yarn build`
- `yarn serve`
- Hit `http://localhost:3000/blog/index.html`

Exact error: `RouteData or withRouteData couldn't find any props for path: blog/index.html. You are either missing a route.getData function or you are relying on RouteData/withRouteData where you don't need to.`
