### ISSUE TITLE
cli start error

### ISSUE THREAD

**Issue by matteofrana** [nozzle/react-static#929] opened 2018-12-29 18:42 UTC
### Are you reporting a bug?
Yes, maybe related to my environment

### Problem description
The CLI command `start` returns an error on a newly created project.

```
MacBook-Pro-di-Matteo:rstatic6 matteo$ yarn start
yarn run v1.12.3
$ react-static start
  Error: Cannot find module 'react-static/babel-preset.js' from '/Users/matteo/D  ocuments/Development/rstatic6'
  
  - sync.js:43 Function.module.exports [as sync]
    [rstatic6]/[resolve]/lib/sync.js:43:15
  
  - plugins.js:101 resolveStandardizedName
    [rstatic6]/[@babel]/core/lib/config/files/plugins.js:101:31
  
  - plugins.js:58 resolvePreset
    [rstatic6]/[@babel]/core/lib/config/files/plugins.js:58:10
  
  - plugins.js:77 loadPreset
    [rstatic6]/[@babel]/core/lib/config/files/plugins.js:77:20
  
  - config-descriptors.js:154 createDescriptor
    [rstatic6]/[@babel]/core/lib/config/config-descriptors.js:154:9
  
  - config-descriptors.js:109 items.map
    [rstatic6]/[@babel]/core/lib/config/config-descriptors.js:109:50
  
  - Array.map
  
  - config-descriptors.js:109 createDescriptors
    [rstatic6]/[@babel]/core/lib/config/config-descriptors.js:109:29
  
  - config-descriptors.js:101 createPresetDescriptors
    [rstatic6]/[@babel]/core/lib/config/config-descriptors.js:101:10
  
  - config-descriptors.js:47 presets
    [rstatic6]/[@babel]/core/lib/config/config-descriptors.js:47:19
  
  - config-chain.js:320 mergeChainOpts
    [rstatic6]/[@babel]/core/lib/config/config-chain.js:320:26
  
  - config-chain.js:283 
    [rstatic6]/[@babel]/core/lib/config/config-chain.js:283:7
  
  - config-chain.js:120 buildRootChain
    [rstatic6]/[@babel]/core/lib/config/config-chain.js:120:22
  
  - partial.js:85 loadPrivatePartialConfig
    [rstatic6]/[@babel]/core/lib/config/partial.js:85:55
  
  - full.js:43 loadFullConfig
    [rstatic6]/[@babel]/core/lib/config/full.js:43:39
  
  - index.js:27 loadOptions
    [rstatic6]/[@babel]/core/lib/config/index.js:27:36
  
  - index.js:231 OptionManager.init
    [rstatic6]/[@babel]/core/lib/index.js:231:36
  
  - node.js:61 compile
    [rstatic6]/[@babel]/register/lib/node.js:61:42
  
  - node.js:102 compileHook
    [rstatic6]/[@babel]/register/lib/node.js:102:12
  
  - index.js:77 Module._compile
    [rstatic6]/[pirates]/lib/index.js:77:29
  
  - loader.js:700 Module._extensions..js
    internal/modules/cjs/loader.js:700:10
  
  - index.js:88 Object.newLoader [as .js]
    [rstatic6]/[pirates]/lib/index.js:88:7
  
  - loader.js:599 Module.load
    internal/modules/cjs/loader.js:599:32
  
  - loader.js:538 tryModuleLoad
    internal/modules/cjs/loader.js:538:12
  
  - loader.js:530 Function.Module._load
    internal/modules/cjs/loader.js:530:3
  
  - loader.js:637 Module.require
    internal/modules/cjs/loader.js:637:17
  
  - helpers.js:20 require
    internal/modules/cjs/helpers.js:20:18
  
  - getConfig.js:328 _callee3$
    [rstatic6]/[react-static]/lib/static/getConfig.js:328:22
  
  - runtime.js:62 tryCatch
    [rstatic6]/[regenerator-runtime]/runtime.js:62:40
  
  - runtime.js:288 Generator.invoke [as _invoke]
    [rstatic6]/[regenerator-runtime]/runtime.js:288:22
  
  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [rstatic6]/[regenerator-runtime]/runtime.js:114:21
  
  - getConfig.js:46 asyncGeneratorStep
    [rstatic6]/[react-static]/lib/static/getConfig.js:46:103
  
  - getConfig.js:48 _next
    [rstatic6]/[react-static]/lib/static/getConfig.js:48:194
  
  - getConfig.js:48 
    [rstatic6]/[react-static]/lib/static/getConfig.js:48:364
  
  - new Promise
  
  - getConfig.js:48 
    [rstatic6]/[react-static]/lib/static/getConfig.js:48:97
  
  - getConfig.js:346 buildConfigFromPath
    [rstatic6]/[react-static]/lib/static/getConfig.js:346:18
  
  - getConfig.js:368 _callee5$
    [rstatic6]/[react-static]/lib/static/getConfig.js:368:20
  
  - runtime.js:62 tryCatch
    [rstatic6]/[regenerator-runtime]/runtime.js:62:40
  
  - runtime.js:288 Generator.invoke [as _invoke]
    [rstatic6]/[regenerator-runtime]/runtime.js:288:22
  
  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [rstatic6]/[regenerator-runtime]/runtime.js:114:21
  
  - getConfig.js:46 asyncGeneratorStep
    [rstatic6]/[react-static]/lib/static/getConfig.js:46:103
  
  - getConfig.js:48 _next
    [rstatic6]/[react-static]/lib/static/getConfig.js:48:194
  
  - getConfig.js:48 
    [rstatic6]/[react-static]/lib/static/getConfig.js:48:364
  
  - new Promise
  
  - getConfig.js:48 
    [rstatic6]/[react-static]/lib/static/getConfig.js:48:97
  
  - getConfig.js:417 getConfig
    [rstatic6]/[react-static]/lib/static/getConfig.js:417:23
  
  - start.js:62 Object._callee3$
    [rstatic6]/[react-static]/lib/commands/start.js:62:42
  
  - runtime.js:62 tryCatch
    [rstatic6]/[regenerator-runtime]/runtime.js:62:40
  
  - runtime.js:288 Generator.invoke [as _invoke]
    [rstatic6]/[regenerator-runtime]/runtime.js:288:22
  
  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [rstatic6]/[regenerator-runtime]/runtime.js:114:21
  

  Error: Cannot find module 'react-static/babel-preset.js' from '/Users/matteo/D  ocuments/Development/rstatic6'
  
  - sync.js:43 Function.module.exports [as sync]
    [rstatic6]/[resolve]/lib/sync.js:43:15
  
  - plugins.js:101 resolveStandardizedName
    [rstatic6]/[@babel]/core/lib/config/files/plugins.js:101:31
  
  - plugins.js:58 resolvePreset
    [rstatic6]/[@babel]/core/lib/config/files/plugins.js:58:10
  
  - plugins.js:77 loadPreset
    [rstatic6]/[@babel]/core/lib/config/files/plugins.js:77:20
  
  - config-descriptors.js:154 createDescriptor
    [rstatic6]/[@babel]/core/lib/config/config-descriptors.js:154:9
  
  - config-descriptors.js:109 items.map
    [rstatic6]/[@babel]/core/lib/config/config-descriptors.js:109:50
  
  - Array.map
  
  - config-descriptors.js:109 createDescriptors
    [rstatic6]/[@babel]/core/lib/config/config-descriptors.js:109:29
  
  - config-descriptors.js:101 createPresetDescriptors
    [rstatic6]/[@babel]/core/lib/config/config-descriptors.js:101:10
  
  - config-descriptors.js:47 presets
    [rstatic6]/[@babel]/core/lib/config/config-descriptors.js:47:19
  
  - config-chain.js:320 mergeChainOpts
    [rstatic6]/[@babel]/core/lib/config/config-chain.js:320:26
  
  - config-chain.js:283 
    [rstatic6]/[@babel]/core/lib/config/config-chain.js:283:7
  
  - config-chain.js:120 buildRootChain
    [rstatic6]/[@babel]/core/lib/config/config-chain.js:120:22
  
  - partial.js:85 loadPrivatePartialConfig
    [rstatic6]/[@babel]/core/lib/config/partial.js:85:55
  
  - full.js:43 loadFullConfig
    [rstatic6]/[@babel]/core/lib/config/full.js:43:39
  
  - index.js:27 loadOptions
    [rstatic6]/[@babel]/core/lib/config/index.js:27:36
  
  - index.js:231 OptionManager.init
    [rstatic6]/[@babel]/core/lib/index.js:231:36
  
  - node.js:61 compile
    [rstatic6]/[@babel]/register/lib/node.js:61:42
  
  - node.js:102 compileHook
    [rstatic6]/[@babel]/register/lib/node.js:102:12
  
  - index.js:77 Module._compile
    [rstatic6]/[pirates]/lib/index.js:77:29
  
  - loader.js:700 Module._extensions..js
    internal/modules/cjs/loader.js:700:10
  
  - index.js:88 Object.newLoader [as .js]
    [rstatic6]/[pirates]/lib/index.js:88:7
  
  - loader.js:599 Module.load
    internal/modules/cjs/loader.js:599:32
  
  - loader.js:538 tryModuleLoad
    internal/modules/cjs/loader.js:538:12
  
  - loader.js:530 Function.Module._load
    internal/modules/cjs/loader.js:530:3
  
  - loader.js:637 Module.require
    internal/modules/cjs/loader.js:637:17
  
  - helpers.js:20 require
    internal/modules/cjs/helpers.js:20:18
  
  - getConfig.js:328 _callee3$
    [rstatic6]/[react-static]/lib/static/getConfig.js:328:22
  
  - runtime.js:62 tryCatch
    [rstatic6]/[regenerator-runtime]/runtime.js:62:40
  
  - runtime.js:288 Generator.invoke [as _invoke]
    [rstatic6]/[regenerator-runtime]/runtime.js:288:22
  
  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [rstatic6]/[regenerator-runtime]/runtime.js:114:21
  
  - getConfig.js:46 asyncGeneratorStep
    [rstatic6]/[react-static]/lib/static/getConfig.js:46:103
  
  - getConfig.js:48 _next
    [rstatic6]/[react-static]/lib/static/getConfig.js:48:194
  
  - getConfig.js:48 
    [rstatic6]/[react-static]/lib/static/getConfig.js:48:364
  
  - new Promise
  
  - getConfig.js:48 
    [rstatic6]/[react-static]/lib/static/getConfig.js:48:97
  
  - getConfig.js:346 buildConfigFromPath
    [rstatic6]/[react-static]/lib/static/getConfig.js:346:18
  
  - getConfig.js:390 FSWatcher._callee4$
    [rstatic6]/[react-static]/lib/static/getConfig.js:390:32
  
  - runtime.js:62 tryCatch
    [rstatic6]/[regenerator-runtime]/runtime.js:62:40
  
  - runtime.js:288 Generator.invoke [as _invoke]
    [rstatic6]/[regenerator-runtime]/runtime.js:288:22
  
  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [rstatic6]/[regenerator-runtime]/runtime.js:114:21
  
  - getConfig.js:46 asyncGeneratorStep
    [rstatic6]/[react-static]/lib/static/getConfig.js:46:103
  
  - getConfig.js:48 _next
    [rstatic6]/[react-static]/lib/static/getConfig.js:48:194
  
  - getConfig.js:48 
    [rstatic6]/[react-static]/lib/static/getConfig.js:48:364
  
  - new Promise
  
  - getConfig.js:48 FSWatcher.<anonymous>
    [rstatic6]/[react-static]/lib/static/getConfig.js:48:97
  
  - events.js:182 FSWatcher.emit
    events.js:182:13
  
  - index.js:200 FSWatcher.<anonymous>
    [rstatic6]/[chokidar]/index.js:200:38
  
  - index.js:241 FSWatcher._emit
    [rstatic6]/[chokidar]/index.js:241:5
  
  - fsevents-handler.js:329 FSWatcher.<anonymous>
    [rstatic6]/[chokidar]/lib/fsevents-handler.js:329:12
  
  - fsevents-handler.js:378 FSWatcher.<anonymous>
    [rstatic6]/[chokidar]/lib/fsevents-handler.js:378:7
  

  TypeError: Cannot read property 'DIST' of undefined
  
  - start.js:85 _callee2$
    [rstatic6]/[react-static]/lib/commands/start.js:85:69
  
  - runtime.js:62 tryCatch
    [rstatic6]/[regenerator-runtime]/runtime.js:62:40
  
  - runtime.js:288 Generator.invoke [as _invoke]
    [rstatic6]/[regenerator-runtime]/runtime.js:288:22
  
  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [rstatic6]/[regenerator-runtime]/runtime.js:114:21
  
  - start.js:24 asyncGeneratorStep
    [rstatic6]/[react-static]/lib/commands/start.js:24:103
  
  - start.js:26 _next
    [rstatic6]/[react-static]/lib/commands/start.js:26:194
  
  - start.js:26 
    [rstatic6]/[react-static]/lib/commands/start.js:26:364
  
  - new Promise
  
  - start.js:26 
    [rstatic6]/[react-static]/lib/commands/start.js:26:97
  
  - start.js:160 
    [rstatic6]/[react-static]/lib/commands/start.js:160:30
  
  - getConfig.js:394 FSWatcher._callee4$
    [rstatic6]/[react-static]/lib/static/getConfig.js:394:42
  
  - runtime.js:62 tryCatch
    [rstatic6]/[regenerator-runtime]/runtime.js:62:40
  
  - runtime.js:288 Generator.invoke [as _invoke]
    [rstatic6]/[regenerator-runtime]/runtime.js:288:22
  
  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [rstatic6]/[regenerator-runtime]/runtime.js:114:21
  
  - getConfig.js:46 asyncGeneratorStep
    [rstatic6]/[react-static]/lib/static/getConfig.js:46:103
  
  - getConfig.js:48 _next
    [rstatic6]/[react-static]/lib/static/getConfig.js:48:194
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
```

### Environment

1.  `react-static -V`: 6.0.18
2.  `node -v`: 10.9.0
3.  `npm -v`: 6.5.0;
3b. `yarn -v`: 1.12.3;
4.  Operating system: MacOs Mojave (10.14.1)
5.  Browser and version (if relevant): -

### Steps to Reproduce the problem

- Just upgraded react-static to v6
- I created a new project (basic template)
- I tried to start it.

I'm almost sure it is bound to my environment, otherwise you would have already spotted it, but I cannot understand what could it be.

**Comment by gristleism** [comment] 2018-12-29 20:18
Having the same issue with a *very* similar environment, my info below.

## Environment
1. `react-static -v`
6.0.18
2. `node -v`
v10.9.0
3. `npm -v`
6.2.0
3b. `yarn -v`
4. Operating System: MacOs Mojave 10.14.2

##Steps to Reproduce the problem
- Upgraded to react-static v6 ( `npm -g i react-static` ) 
- `react-static create`, select `basic` template 
- `yarn run start`

## Error 

```
Error: Cannot find module 'react-static/babel-preset.js' from '/Users/ian/Glover/Work/  Professional/nick-miller/nick-miller-portfolio'

  - sync.js:43 Function.module.exports [as sync]
    [nick-miller-portfolio]/[resolve]/lib/sync.js:43:15

  - plugins.js:101 resolveStandardizedName
    [nick-miller-portfolio]/[@babel]/core/lib/config/files/plugins.js:101:31

  - plugins.js:58 resolvePreset
    [nick-miller-portfolio]/[@babel]/core/lib/config/files/plugins.js:58:10

  - plugins.js:77 loadPreset
    [nick-miller-portfolio]/[@babel]/core/lib/config/files/plugins.js:77:20

  - config-descriptors.js:154 createDescriptor
    [nick-miller-portfolio]/[@babel]/core/lib/config/config-descriptors.js:154:9

  - config-descriptors.js:109 items.map
    [nick-miller-portfolio]/[@babel]/core/lib/config/config-descriptors.js:109:50

  - Array.map

  - config-descriptors.js:109 createDescriptors
    [nick-miller-portfolio]/[@babel]/core/lib/config/config-descriptors.js:109:29

  - config-descriptors.js:101 createPresetDescriptors
    [nick-miller-portfolio]/[@babel]/core/lib/config/config-descriptors.js:101:10

  - config-descriptors.js:47 presets
    [nick-miller-portfolio]/[@babel]/core/lib/config/config-descriptors.js:47:19

  - config-chain.js:320 mergeChainOpts
    [nick-miller-portfolio]/[@babel]/core/lib/config/config-chain.js:320:26

  - config-chain.js:283
    [nick-miller-portfolio]/[@babel]/core/lib/config/config-chain.js:283:7

  - config-chain.js:120 buildRootChain
    [nick-miller-portfolio]/[@babel]/core/lib/config/config-chain.js:120:22

  - partial.js:85 loadPrivatePartialConfig
    [nick-miller-portfolio]/[@babel]/core/lib/config/partial.js:85:55

  - full.js:43 loadFullConfig
    [nick-miller-portfolio]/[@babel]/core/lib/config/full.js:43:39

  - index.js:27 loadOptions
    [nick-miller-portfolio]/[@babel]/core/lib/config/index.js:27:36

  - index.js:231 OptionManager.init
    [nick-miller-portfolio]/[@babel]/core/lib/index.js:231:36

  - node.js:61 compile
    [nick-miller-portfolio]/[@babel]/register/lib/node.js:61:42

  - node.js:102 compileHook
    [nick-miller-portfolio]/[@babel]/register/lib/node.js:102:12

  - index.js:77 Module._compile
    [nick-miller-portfolio]/[pirates]/lib/index.js:77:29

  - loader.js:700 Module._extensions..js
    internal/modules/cjs/loader.js:700:10

  - index.js:88 Object.newLoader [as .js]
    [nick-miller-portfolio]/[pirates]/lib/index.js:88:7

  - loader.js:599 Module.load
    internal/modules/cjs/loader.js:599:32

  - loader.js:538 tryModuleLoad
    internal/modules/cjs/loader.js:538:12

  - loader.js:530 Function.Module._load
    internal/modules/cjs/loader.js:530:3

  - loader.js:637 Module.require
    internal/modules/cjs/loader.js:637:17

  - helpers.js:20 require
    internal/modules/cjs/helpers.js:20:18

  - getConfig.js:328 _callee3$
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:328:22

  - runtime.js:62 tryCatch
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:62:40

  - runtime.js:288 Generator.invoke [as _invoke]
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:288:22

  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:114:21

  - getConfig.js:46 asyncGeneratorStep
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:46:103

  - getConfig.js:48 _next
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:48:194

  - getConfig.js:48
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:48:364

  - new Promise

  - getConfig.js:48
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:48:97

  - getConfig.js:346 buildConfigFromPath
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:346:18

  - getConfig.js:368 _callee5$
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:368:20

  - runtime.js:62 tryCatch
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:62:40

  - runtime.js:288 Generator.invoke [as _invoke]
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:288:22

  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:114:21

  - getConfig.js:46 asyncGeneratorStep
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:46:103

  - getConfig.js:48 _next
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:48:194

  - getConfig.js:48
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:48:364

  - new Promise

  - getConfig.js:48
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:48:97

  - getConfig.js:417 getConfig
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:417:23

  - start.js:62 Object._callee3$
    [nick-miller-portfolio]/[react-static]/lib/commands/start.js:62:42

  - runtime.js:62 tryCatch
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:62:40

  - runtime.js:288 Generator.invoke [as _invoke]
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:288:22

  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:114:21


  Error: Cannot find module 'react-static/babel-preset.js' from '/Users/ian/Glover/Work/  Professional/nick-miller/nick-miller-portfolio'

  - sync.js:43 Function.module.exports [as sync]
    [nick-miller-portfolio]/[resolve]/lib/sync.js:43:15

  - plugins.js:101 resolveStandardizedName
    [nick-miller-portfolio]/[@babel]/core/lib/config/files/plugins.js:101:31

  - plugins.js:58 resolvePreset
    [nick-miller-portfolio]/[@babel]/core/lib/config/files/plugins.js:58:10

  - plugins.js:77 loadPreset
    [nick-miller-portfolio]/[@babel]/core/lib/config/files/plugins.js:77:20

  - config-descriptors.js:154 createDescriptor
    [nick-miller-portfolio]/[@babel]/core/lib/config/config-descriptors.js:154:9

  - config-descriptors.js:109 items.map
    [nick-miller-portfolio]/[@babel]/core/lib/config/config-descriptors.js:109:50

  - Array.map

  - config-descriptors.js:109 createDescriptors
    [nick-miller-portfolio]/[@babel]/core/lib/config/config-descriptors.js:109:29

  - config-descriptors.js:101 createPresetDescriptors
    [nick-miller-portfolio]/[@babel]/core/lib/config/config-descriptors.js:101:10

  - config-descriptors.js:47 presets
    [nick-miller-portfolio]/[@babel]/core/lib/config/config-descriptors.js:47:19

  - config-chain.js:320 mergeChainOpts
    [nick-miller-portfolio]/[@babel]/core/lib/config/config-chain.js:320:26

  - config-chain.js:283
    [nick-miller-portfolio]/[@babel]/core/lib/config/config-chain.js:283:7

  - config-chain.js:120 buildRootChain
    [nick-miller-portfolio]/[@babel]/core/lib/config/config-chain.js:120:22

  - partial.js:85 loadPrivatePartialConfig
    [nick-miller-portfolio]/[@babel]/core/lib/config/partial.js:85:55

  - full.js:43 loadFullConfig
    [nick-miller-portfolio]/[@babel]/core/lib/config/full.js:43:39

  - index.js:27 loadOptions
    [nick-miller-portfolio]/[@babel]/core/lib/config/index.js:27:36

  - index.js:231 OptionManager.init
    [nick-miller-portfolio]/[@babel]/core/lib/index.js:231:36

  - node.js:61 compile
    [nick-miller-portfolio]/[@babel]/register/lib/node.js:61:42

  - node.js:102 compileHook
    [nick-miller-portfolio]/[@babel]/register/lib/node.js:102:12

  - index.js:77 Module._compile
    [nick-miller-portfolio]/[pirates]/lib/index.js:77:29

  - loader.js:700 Module._extensions..js
    internal/modules/cjs/loader.js:700:10

  - index.js:88 Object.newLoader [as .js]
    [nick-miller-portfolio]/[pirates]/lib/index.js:88:7

  - loader.js:599 Module.load
    internal/modules/cjs/loader.js:599:32

  - loader.js:538 tryModuleLoad
    internal/modules/cjs/loader.js:538:12

  - loader.js:530 Function.Module._load
    internal/modules/cjs/loader.js:530:3

  - loader.js:637 Module.require
    internal/modules/cjs/loader.js:637:17

  - helpers.js:20 require
    internal/modules/cjs/helpers.js:20:18

  - getConfig.js:328 _callee3$
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:328:22

  - runtime.js:62 tryCatch
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:62:40

  - runtime.js:288 Generator.invoke [as _invoke]
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:288:22

  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:114:21

  - getConfig.js:46 asyncGeneratorStep
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:46:103

  - getConfig.js:48 _next
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:48:194

  - getConfig.js:48
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:48:364

  - new Promise

  - getConfig.js:48
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:48:97

  - getConfig.js:346 buildConfigFromPath
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:346:18

  - getConfig.js:390 FSWatcher._callee4$
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:390:32

  - runtime.js:62 tryCatch
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:62:40

  - runtime.js:288 Generator.invoke [as _invoke]
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:288:22

  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:114:21

  - getConfig.js:46 asyncGeneratorStep
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:46:103

  - getConfig.js:48 _next
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:48:194

  - getConfig.js:48
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:48:364

  - new Promise

  - getConfig.js:48 FSWatcher.<anonymous>
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:48:97

  - events.js:182 FSWatcher.emit
    events.js:182:13

  - index.js:200 FSWatcher.<anonymous>
    [nick-miller-portfolio]/[chokidar]/index.js:200:38

  - index.js:241 FSWatcher._emit
    [nick-miller-portfolio]/[chokidar]/index.js:241:5

  - fsevents-handler.js:329 FSWatcher.<anonymous>
    [nick-miller-portfolio]/[chokidar]/lib/fsevents-handler.js:329:12

  - fsevents-handler.js:378 FSWatcher.<anonymous>
    [nick-miller-portfolio]/[chokidar]/lib/fsevents-handler.js:378:7


  TypeError: Cannot read property 'DIST' of undefined

  - start.js:85 _callee2$
    [nick-miller-portfolio]/[react-static]/lib/commands/start.js:85:69

  - runtime.js:62 tryCatch
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:62:40

  - runtime.js:288 Generator.invoke [as _invoke]
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:288:22

  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:114:21

  - start.js:24 asyncGeneratorStep
    [nick-miller-portfolio]/[react-static]/lib/commands/start.js:24:103

  - start.js:26 _next
    [nick-miller-portfolio]/[react-static]/lib/commands/start.js:26:194

  - start.js:26
    [nick-miller-portfolio]/[react-static]/lib/commands/start.js:26:364

  - new Promise

  - start.js:26
    [nick-miller-portfolio]/[react-static]/lib/commands/start.js:26:97

  - start.js:160
    [nick-miller-portfolio]/[react-static]/lib/commands/start.js:160:30

  - getConfig.js:394 FSWatcher._callee4$
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:394:42

  - runtime.js:62 tryCatch
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:62:40

  - runtime.js:288 Generator.invoke [as _invoke]
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:288:22

  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [nick-miller-portfolio]/[regenerator-runtime]/runtime.js:114:21

  - getConfig.js:46 asyncGeneratorStep
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:46:103

  - getConfig.js:48 _next
    [nick-miller-portfolio]/[react-static]/lib/static/getConfig.js:48:194

  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
```

**Comment by graemefoster** [comment] 2018-12-30 00:53
Same problem - brand new react-static site, basic template. Same error message.
Have never had react-static on my machine before.

**Comment by graemefoster** [comment] 2018-12-30 00:57
FWIW I followed this https://github.com/nozzle/react-static/issues/913 and it started working.

**Comment by tannerlinsley** [comment] 2018-12-30 16:32
Does upgrading to the latest version fix it?

**Comment by tannerlinsley** [comment] 2018-12-30 16:33
Looks like I'll need to double check the release.

**Comment by matteofrana** [comment] 2018-12-30 17:46
It must be the yarn.lock file.
If I remove the `yarn.lock` file and the `node_modules` folder and re-install the node modules with `yarn` than it's all right.

**Comment by nozzle** [comment] 2018-12-30 20:21
This should be fixed in the latest release

**Closed by nozzle** 2018-12-30 20:21 UTC

**Comment by efleurine** [comment] 2019-01-26 11:48
Hi everyone,

just to let you know

I just got this error with a fresh global installation of react-static with both stress & typescript template.
