### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by max80713** [nozzle/react-static#906] opened 2018-12-20 05:45 UTC
The problem still exists after updating to the latest version(v6.0.11). See: [#883](https://github.com/nozzle/react-static/issues/883)

### Environment

1. react-static -V: 6.0.11
2. node -v: v8.9.0
3. npm -v: 5.5.1
4. Operating system: macOS Mojave 10.14
5. Browser and version (if relevant):

### Steps to Reproduce the problem

1. react-static create
2. yarn build
3. yarn serve

#### result

navigate to http://localhost:3000/blog and show in browser:

Oh-no! Something’s gone wrong!

Reload Component
TypeError: Cannot read property 'map' of undefined

    in a
    in F
    in q
    in DefaultRouter
    in RouterScroller
    in s
    in ErrorBoundary
    in Router
    in Unknown
    in Unknown

### Expected Behavior

A normal post page just like the one after yarn start

### Reproducible Demo

I have no demo, but it is just the react-static app using the basic template.

**Comment by Vinnl** [comment] 2018-12-20 09:19
Interesting: it's the destructuring that breaks it, i.e. in this case

```javascript
export default withRouteData(({ posts }) => (
  <div>
    <h1>It's blog time.</h1>
    <br />
    All Posts:
    <ul>
      {posts.map(post => (
        <li key={post.id}>
          <Link to={`/blog/post/${post.id}/`}>{post.title}</Link>
        </li>
      ))}
    </ul>
  </div>
))
```

`posts` is undefined, but in this case

```javascript
export default withRouteData((routeData) => (
  <div>
    <h1>It's blog time.</h1>
    <br />
    All Posts:
    <ul>
      {routeData.posts.map(post => (
        <li key={post.id}>
          <Link to={`/blog/post/${post.id}/`}>{post.title}</Link>
        </li>
      ))}
    </ul>
  </div>
))

```

`routeData.posts` is not, and the page does not break.

**Comment by paavohuhtala** [comment] 2018-12-20 19:10
I can confirm the issue still exists with https://opensage.github.io ([source code](https://github.com/OpenSAGE/opensage.github.io/tree/gh-pages)). For instance, navigate to https://opensage.github.io/blog/ and click any of the articles. The page will crash because of missing route data. Also, navigating from the front page to the blog post listing will result in an empty listing.

I've upgraded to 6.0.11 and it works as expected in development mode.

**Comment by paavohuhtala** [comment] 2018-12-20 19:43
This also happens with a brand new site generated from `react-static create`, choosing basic template.

Don't take this the wrong way, but for the about a week I've been testing `react-static` I haven't gotten it to work properly a single time, on 3 different computers and/or a CI server.

Does anyone actually use this in production? Are all of my computers and CI instances cursed, or is this tool just completely broken for everyone right now?

**Comment by Vinnl** [comment] 2018-12-20 19:48
@paavohuhtala The original report already stated that this was the case on the basic template.

Note that v6 has just been released, and it appears that there are still quite a few kinks that are to be worked out. I haven't been able to upgrade my sites to v6 yet, but v5 is still running smoothly in production, so you mind want to stick to that for now.

**Comment by paavohuhtala** [comment] 2018-12-20 19:55
Yeah, perhaps I chose a wrong time to try this. As an outsider without prior experience with the tool I expected what Yarn installed (6) to work at least at a basic level, as it's marked as stable. I understand that every release has its challenges and new bugs come up and maintaining this isn't anyone's dayjob, but I'm just surprised that 6 is marketed as stable even though it literally doesn't work.

**Comment by georgehenderson** [comment] 2018-12-20 21:35
I was able to get the example "working" by adjusting `static.config.js` and using localProps (undocumented maybe for good reason).

```javascript
import axios from 'axios'

export default {
  getSiteData: () => ({
    title: 'React Static',
  }),
  getRoutes: async () => {
    const { data: posts } = await axios.get(
      'https://jsonplaceholder.typicode.com/posts'
    )
    return [
      {
        path: '/blog',
        localProps: {posts},
        getData: () => ({
          posts,
        }),
        children: posts.map(post => ({
          path: `/post/${post.id}`,
          component: 'src/containers/Post',
          localProps: {post},
          getData: () => ({
            post,
          }),
        })),
      },
    ]
  },
}
```

Definitely seems like the shared data hashes to flush out allProps is borked, but I don't know the codebase well enough to say for sure.

**Comment by georgehenderson** [comment] 2018-12-20 21:40
Furthermore, it seems like the routeInfo when built does not have all the info it needs. And so navigating to a new route through the Link component is busted, hard page reloads work though since the data for the route does get serialized into the markup. My comment above shims the data for the route from localProps but id expect the object returned from getData to just work so there probably is a bug.

**Comment by ScriptedAlchemy** [comment] 2018-12-21 08:04
This could be related somehow to either the object being mutated. Something myself and James call “build the plane as it flys” causing it to both work and not work during runtime.  

Or Babel destructuring is messed up?

**Comment by tannerlinsley** [comment] 2018-12-21 17:57
There was a gaping bug found with routeInfo in both the dev server and production builds and a patch has been released. Please upgrade to the latest version and verify the issue again.

**Comment by georgehenderson** [comment] 2018-12-21 20:14
Fixed!

**Comment by georgehenderson** [comment] 2018-12-21 20:21
I am seeing new error in the console for production builds. Its trying to reference `routeInfo.fullData` but routInfo is the markup string.

<img width="894" alt="screen shot 2018-12-21 at 2 19 47 pm" src="https://user-images.githubusercontent.com/1379792/50362052-bc284880-052b-11e9-8444-76a1af501fc1.png">

**Comment by tannerlinsley** [comment] 2018-12-21 20:31
Can you point us to your site? My guess is that your server isn't serving the JSON files correctly (and redirecting the requests of routeInfo.json files to your index.html or something similar)

**Comment by georgehenderson** [comment] 2018-12-21 20:36
@tannerlinsley Oh I see, what's happening. I have a non-static route called `/account` that lives in the header. It looks like it is trying to find routeInfo.json for that route and my server is redirecting a catchall route back to index.html. Is it expected for react-static to try to find routeInfo for routes it doesnt own? Should my server expect this and throw a 404?

**Comment by tannerlinsley** [comment] 2018-12-21 20:39
Technically no, the fact that RS tries to load routeInfo for that path isn't a bad thing. When it 404's it merely assumes that it isn't a static-progressive path. It get's marked as such and isn't requested going forward. Unfortunately, without loading a massive JSON file of every possible static route into the runtime, this is the best way to determine if a path is an RS one or not.

**Comment by tannerlinsley** [comment] 2018-12-21 20:40
At one point, we *did* load a JSON file with all possible routes, but for even big-ish sites, it quickly became a performance bottleneck.

**Comment by tannerlinsley** [comment] 2018-12-21 20:42
Do you get any errors/warnings on build?

**Comment by georgehenderson** [comment] 2018-12-21 20:46
Nope no errors. Returning a 404 fixed the issue. Thanks!

The only other issue i'm seeing is navigating back or forward via the browser arrows to a non-static route borks and throws an error.

<img width="1698" alt="screen shot 2018-12-21 at 2 44 48 pm" src="https://user-images.githubusercontent.com/1379792/50362893-28587b80-052f-11e9-9356-5700216e24bd.png">

**Comment by tannerlinsley** [comment] 2018-12-21 20:47
Let me look into this for a second...

**Comment by tannerlinsley** [comment] 2018-12-21 21:10
How are you doing your dynamic routes? We're still working on an example for this ourselves ([interim example is located here](https://github.com/nozzle/react-static/blob/master/docs/guides/dynamic-routes-reach-router.md)).

**Comment by georgehenderson** [comment] 2018-12-21 21:14
Here's the gist, all static routes are a single reach router `default` route.

```javascript
import React from 'react';
import {Router, Link} from '@reach/router';
import {Root, Routes} from 'react-static';
import Account from './containers/Account';
import './app.css';

const StaticRoutes = () => {
  return <Routes />;
};

function App() {
  return (
    <Root>
      <nav>
        <Link to="/blog">Blog</Link>
        <Link to="/account">Account</Link>
      </nav>
      <div className="content">
        <Router>
          <Account path="account" />
          <StaticRoutes default />
        </Router>
      </div>
    </Root>
  );
}

export default App;
```

And the account page

```javascript
import React, {Component} from 'react';

class Account extends Component {
  state = {};
  render() {
    return (
      <div><h1>Account</h1></div>
    );
  }
}

export default Account;
```

**Comment by tannerlinsley** [comment] 2018-12-21 21:15
Awesome. That's what I'm testing with. Stay tuned...

**Comment by tannerlinsley** [comment] 2018-12-21 21:49
Alright, just did a patch release to handle an unhandled edge case for dynamic routes and 404 templates. Can you upgrade and test your dynamic route again?

**Comment by georgehenderson** [comment] 2018-12-21 21:56
Nice! Verified fixed in both dev and prod builds. Thanks for patching, and being so responsive.

**Comment by tannerlinsley** [comment] 2018-12-21 22:14
Awesome! Thanks for helping. Spread the good word!

**Closed by tannerlinsley** 2018-12-21 22:14 UTC
Labels: bug, fix-released

**Comment by georgehenderson** [comment] 2018-12-21 23:15
One thing I did find useful with dynamic route rendering is to create a placeholder route to house a shell of the application. Rendering the root path can cause issues with flashing if there is content baked into the markup. My `Shell` component looks like this:
```javascript
import React, {Component} from 'react';

class Shell extends Component {
  state = {};
  render() {
    return (
      <div></div>
    );
  }
}

export default Shell;

// static.config.js
{
    path: '/shell',
    component: 'src/containers/Shell'
}

//  server.js
app.get('*', (req, res) => {
  if (/routeInfo\.json/.test(req.url)) {
    res.status(404).send('Not found');
    return;
  }
  res.status(200).sendFile('index.html', {root: '../dist/shell'});
});
```

**Comment by tannerlinsley** [comment] 2018-12-21 23:41
That's interesting. Yeah there are so many different ways of mixing dynamic and static content. It really depends on each project and situation, but like you've found, there's usually a good solution to each of those situations.
