### ISSUE TITLE
Add code splitting

### ISSUE THREAD

**Issue by cr101** [nozzle/react-static#32] opened 2017-10-12 10:36 UTC
Is there a way to implement Code Splitting like in [this example](https://serverless-stack.com/chapters/code-splitting-in-create-react-app.html)?

**Comment by derekperkins** [comment] 2017-10-12 16:00
It's certainly possible to do, but not built in yet. In our experience, most marketing sites tend to have 5-7 page templates, in comparison to a full app that likely has hundreds. It's something that we plan to tackle at some point, but for the time being, it feels like a premature optimization.

**Comment by tannerlinsley** [comment] 2017-10-12 19:32
I'll look into this over the next few days. This could be very possible to implement :)

**Comment by tannerlinsley** [comment] 2017-10-24 23:36
Duplicate of #66, which I'm more than happy to discuss, but we're going to close the issue for now and continue the discussion in #66 and on Slack. Thanks.

**Closed by tannerlinsley** 2017-10-24 23:36 UTC
Labels: enhancement
