### ISSUE TITLE
npm run build fails on fresh project

### ISSUE THREAD

**Issue by neilyoung** [nozzle/react-static#1053] opened 2019-03-04 18:18 UTC
After having done a couple of projects with react-static I was trying today to create a "blank" project  named `bla` and `npm run build` it. I'm having changed nothing in the scaffolded files. The build fails 

The error list is insanely long, but this is the top-level error. There is also an "artifact" subdir, which I never have noticed before:

```

ERROR in /Users/me/Documents/bla/artifacts/react-static-templates.js 1:652
Module parse failed: Unexpected token (1:652)
You may need an appropriate loader to handle this file type.


```

react-static version is 5.9.12

Any idea?

**Comment by neilyoung** [comment] 2019-03-04 18:29
Hmm. Took one of my "old" package.json and it compiles. To be continued...

**Comment by neilyoung** [comment] 2019-03-04 18:33
Interesting. I must have kind of a mixed configuration on my machine. react-static -V says 5.9.12. But the scaffolded blank project has a dependency to react-static 6.3.x.

Changed that to
"dependencies": {
    "react-static": "^5.9.7"
  },

and fine. No "artifacts" no problems.

**Comment by evgeny-t** [comment] 2019-03-05 13:39
I've installed react-static@6.3.6, created a new blank project, when I tried npm run build I've got the same error and a stacktrace:

```
  Error: AssertionError [ERR_ASSERTION]: missing path
  
  - module.js:594 Module.require
    module.js:594:3
  
  - module.js:11 require
    internal/module.js:11:18
  
  - exporter.threaded.js:22 require
    [636]/[react-static]/src/static/exporter.threaded.js:22:18
  
  - runtime.js:62 tryCatch
    [636]/[regenerator-runtime]/runtime.js:62:40
  
  - runtime.js:288 Generator.invoke [as _invoke]
    [636]/[regenerator-runtime]/runtime.js:288:22
  
  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [636]/[regenerator-runtime]/runtime.js:114:21
  
  - runtime.js:62 tryCatch
    [636]/[regenerator-runtime]/runtime.js:62:40
  
  - runtime.js:350 maybeInvokeDelegate
    [636]/[regenerator-runtime]/runtime.js:350:18
  
  - runtime.js:262 Generator.invoke [as _invoke]
    [636]/[regenerator-runtime]/runtime.js:262:32
  
  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [636]/[regenerator-runtime]/runtime.js:114:21
  
  - exporter.threaded.js:23 asyncGeneratorStep
    [636]/[react-static]/lib/static/exporter.threaded.js:23:103
  
  - exporter.threaded.js:25 _next
    [636]/[react-static]/lib/static/exporter.threaded.js:25:194
  
  
  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7
```

**Comment by neilyoung** [comment] 2019-03-05 13:45
@evgeny-t Ah, ok. So there might be something with 6.3.6? As said, the scaffolder added a dependency to react-static 6.3.6 to my package.json. After having reverted that manually to 5.9.x (the version I have) everything was fine.

**Comment by evgeny-t** [comment] 2019-03-05 13:57
it's trying to require undefined here https://github.com/nozzle/react-static/blob/v6.3.6/packages/react-static/src/static/exporter.threaded.js#L23

**Comment by evgeny-t** [comment] 2019-03-05 14:49
I was not able to reproduce this in a docker container, both 6.3.6 and 6.1.4 (the version I use) worked well.

**Comment by evgeny-t** [comment] 2019-03-05 15:04
when I used yarn instead of npm it got built without any problem

**Comment by sw-yx** [comment] 2019-03-06 08:27
this is a known issue with npm unfortunately. https://github.com/nozzle/react-static/issues/1027 closing as duplicate. just use yarn for now.

**Closed by sw-yx** 2019-03-06 08:27 UTC
