### ISSUE TITLE
[Bug] Prefetching issues (Cannot read property `templateLoaded` of undefined)

### ISSUE THREAD

**Issue by jxom** [nozzle/react-static#1008] opened 2019-02-07 23:37 UTC
### Reporting a bug?

Hey!

I've been running into an issue where I've been receiving this error when navigating between pages on when running a dev server:

<img width="1052" alt="screen shot 2019-02-08 at 10 32 16 am" src="https://user-images.githubusercontent.com/7336481/52449933-1e491580-2b8d-11e9-9472-2f220aca7e42.png">

Any thoughts on the instances in which this could even occur? Or should we be guarding against `routeInfo` being undefined?

I've currently been in the process of migrating from v5 to v6.

### Environment

```
  System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 2.96 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 63.0.3
    Safari: 12.0
```

of course include any other package versions here if relevant. 

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  Navigate between pages
2.  BOOM!

**Comment by jxom** [comment] 2019-02-08 00:01
I noticed this might be similar to #649. However, I'm not using any dynamic routes.

**Comment by IOIO72** [comment] 2019-02-08 00:33
I'm getting the same error. I found out that this error occurs in version `6.3.4`. If I downgrade to `6.3.3` it doesn't.
@jxom Could you investigate this in your project?

**Comment by IOIO72** [comment] 2019-02-08 00:41
Just guessing that the potential bug could be found here:
https://github.com/nozzle/react-static/compare/v6.3.3...master#diff-499262eac0aff0ac96b9622aaa679aa5

**Comment by IOIO72** [comment] 2019-02-08 00:45
I'm just guessing that the potential bug might be somewhere here:
https://github.com/nozzle/react-static/commit/499343ab1873faf997f738d3c6b6f4e2c6ae0315#diff-499262eac0aff0ac96b9622aaa679aa5

**Comment by jxom** [comment] 2019-02-08 01:04
Downgrading to `6.3.3` seems to fix it!

**Comment by pauloamgomes** [comment] 2019-02-08 19:03
> Downgrading to `6.3.3` seems to fix it!

same here, in my case, seems only to happen in a page with invalid links

**Comment by IOIO72** [comment] 2019-02-11 01:35
It seems to be fixed in `6.3.5`. I guess this issue was covered in fix #981

**Comment by jlee1201** [comment] 2019-02-11 10:51
still get this error in `6.3.5` when running dev server.  I can reproduce this reliably in two different ways (after starting dev server):
1. navigate to a page with links that are invalid (I have lots of these as the site is not feature complete yet), and wait for prefetching to begin.
2. make a code change on a page with invalid links, causing hot module reloading to initiate.  Wait a few seconds for prefetching to begin.

Workaround (?) is to refresh the page in browser after HMR completes (or after page navigation).

**Comment by tannerlinsley** [comment] 2019-02-11 16:59
@jlee1201 Does this error break the page? In development it should be expected for your site to at least *try* fetching the routeInfo and templates for valid links (even if they point to nonexistent pages).

**Comment by bram-l** [comment] 2019-02-12 09:19
Oops.. @krzysztof-pyrzyk-ah I see we were working on the same issue! The fix I just submitted as PR is the same as yours, but I realised the underlying issue here is that 404 route info is not handled correctly in all cases after #992 was merged. This is quite a complex issue though so I hope @tannerlinsley you could also have a look at this!

**Closed** 2019-02-12 16:45 UTC
