### ISSUE TITLE
error retrieving static assets if basePath is set

### ISSUE THREAD

**Issue by phaneendra** [nozzle/react-static#926] opened 2018-12-28 19:48 UTC
### Are you reporting a bug?
Yes

### Environment

1.  `react-static -V`: 6.0.18
2.  `node -v`: v10.13.0
3.  `npm -v`: 6.4.1
4.  Operating system: macOS
5.  Browser and version (if relevant): chrome 

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  Created a new site using `react-static create` basic template
2.  modify static.config.js to include basePath and siteRoot
3.  deploy to gh-pages

### Expected Behavior
Routing should work properly, but get 404 errors in browser console which xhr to retrieve routeInfo.json file.
GET https://phaneendra.github.io/urbanrunners/https://phaneendra.github.io/urbanrunners/blog/routeInfo.json 404

seems the function getRoutePath to strip the path of window.location.origin is not called.

### Reproducible Demo
https://github.com/phaneendra/urbanrunners
http://phaneendra.github.io/urbanrunners/

**Comment by Ziinc** [comment] 2019-01-05 14:54
Seems like your routeInfo.json can be accessed at http://phaneendra.github.io/urbanrunners/blog/routeInfo.json

nothing gets thrown in browser console as well

**Comment by Ziinc** [comment] 2019-01-05 16:12
However, seems like not all static assets are being resolved with basePath:

Navigating to http://phaneendra.github.io/urbanrunners/ and clicking on `About` results in a few files not being able to be loaded.

![image](https://user-images.githubusercontent.com/22714384/50726409-9e6ffb80-1147-11e9-8976-08c5f31b3c4a.png)

**Comment by Ziinc** [comment] 2019-02-09 03:01
Bump. This issue effectively rules out hosting on github/gitlab pages under a basepath, which may hinder adoption when users write docs for projects and host the docs directly on github/gitlab.

**Comment by tannerlinsley** [comment] 2019-04-01 17:27
Please take a look at v7 and confirm that this is still an issue? If it is, reopen this issue and likewise we will be in a better position to fix it with the new v7 architecture. If it's not, then huzzah!

**Closed by tannerlinsley** 2019-04-01 17:27 UTC
Labels: bug

**Comment by lamessaint** [comment] 2019-05-07 20:35
@tannerlinsley the problem is existing yet on 7.0.0

**Comment by JoseFMP** [comment] 2019-05-10 12:55
I confirm. Still there.
