### ISSUE TITLE
[Bug] yarn build exits with code 0 when getRoutes fail

### ISSUE THREAD

**Issue by samidalouche** [nozzle/react-static#1046] opened 2019-02-27 15:27 UTC
### Environment

`npx envinfo --system --npmPackages react* --binaries --npmGlobalPackages react* --browsers` 

```

npx: installed 1 in 2.466s

  System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 244.29 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Browsers:
    Chrome: 72.0.3626.119
    Firefox: 64.0.2
    Safari: 12.0.2
  npmPackages:
    react: ^16.6.3 => 16.7.0
    react-dom: ^16.6.3 => 16.7.0
    react-hot-loader: ^4.3.12 => 4.6.3
    react-static: ^6.0.18 => 6.1.5
  npmGlobalPackages:
    react-static: 6.3.3



```

### Steps to Reproduce the problem

```bash
$ nvm use node
Now using node v10.15.0 (npm v6.4.1)
$ react-static --version
6.3.3
$ react-static create --name=broken
# select basic template

# modify `getRoutes` in static.config.js to break the build
# throw "broken-build"

$ yarn build
yarn run v1.13.0
$ react-static build

=> Info: No 'siteRoot' is defined in 'static.config.js'. This is suggested for absolute urls and a sitemap.xml to be automatically generated.

=> Cleaning dist...
=> [✓] Dist cleaned
=> Building Routes...
  Error: broken-build

✨  Done in 3.73s.
$ echo $?
0
```

### Expected Behavior

return 1

**Comment by tannerlinsley** [comment] 2019-02-27 15:57
Duplicate of #946

**Closed by tannerlinsley** 2019-02-27 15:57 UTC
