### ISSUE TITLE
Is there a changelog?

### ISSUE THREAD

**Issue by coisnepe** [nozzle/react-static#57] opened 2017-10-18 07:47 UTC
Is there an easy way to see what each new version brings?

**Comment by derekperkins** [comment] 2017-10-18 19:41
Duplicate of #31 
@tannerlinsley

**Closed by derekperkins** 2017-10-18 19:41 UTC

**Comment by coisnepe** [comment] 2017-10-19 07:49
My bad, thanks @derekperkins

**Comment by derekperkins** [comment] 2017-10-19 10:31
@coisnepe No worries, it's an important issue that we need to do better on.
