### ISSUE TITLE
[Bug] 404s every page after enabling watch('content') to reloadRoutes() in static.config.js

### ISSUE THREAD

**Issue by theWebalyst** [nozzle/react-static#985] opened 2019-01-22 12:12 UTC
### Are you reporting a bug?

Yes

Note: this issue originally filed on my rs-basic-test repo: https://github.com/theWebalyst/rs-basic-test/issues/1

### Environment

    react-static -V: 6.1.5
    node -v: 8.11.3
    npm -v: 6.4.1
    Operating system: Ubuntu 18.10

### Steps to Reproduce the problem

Starting with the basic template, I made small changes to get it to load content from markdown files by changing the relevant parts, based this other example: https://github.com/tannerlinsley/react-static-markdown (I chose to follow how that loads markdown having first failed to do this based on the code in the react-static archived markdown example).

You can reproduce the error by:

- `git clone https://github.com/theWebalyst/rs-basic-test/ && cd rs-basic-test && git checkout tags/take-content-from-markdown-files -b localtest && yarn && yarn start`
- visit http://localhost:3000/ and confirm Home, About, Blog etc load ok
- remove the comment in static.config.js to enable reloadRoutes() at [line 7](https://github.com/theWebalyst/rs-basic-test/blob/take-content-from-markdown-files/static.config.js#L7)
- things work as expected if you *just edit content*
- until you refresh the page or click on the navigation: Home, About, Blog etc all show a 404 error

I don't see any errors in browser or terminal console (using Firefox), but note that there is still some console.log() debug output generated to the terminal by the build (see static.config.js 15-17)

**Comment by gpoole** [comment] 2019-02-01 03:09
I'm having the same issue, but I don't think it's caused by the call to `reloadRoutes()`. If I make any changes at all to my static.config.js and save I get 404s until I restart the watch server. I've also checked and the same thing happens in the linked example without the `reloadRoutes()` line being uncommented.

**Comment by theWebalyst** [comment] 2019-02-01 12:56
Phew, it isn't just me - always the expectation when learning something new :smile: 

I just updated the OP to reflect that if I start without the `reloadRoutes()` line, do ỳarn start` reload the site (all good), edit `static.config.js` to enable:
```
chokidar.watch('content').on('all', () => reloadRoutes())
```
Then save `static.config.js` it all works. Changes to my content are hot reloaded as expected... *until* I refresh the page, or click on any navigation, or restart `yarn start`. Then it is all 404s again.

I'm not sure if this is consistent with your report @gpoole?

**Comment by gpoole** [comment] 2019-02-04 00:13
Yep, sound like we're having the same problem @theWebalyst. I can reproduce what you described just by starting the server and touching the file without making any changes, so I think it must be something to do with the configuration being reloaded.

**Comment by theWebalyst** [comment] 2019-02-04 15:52
@gpoole if I h understand you, you only get a problem if you edit `static.config.js` after starting `yarn start`, so I'm not sure it's the same problem.

I don't have to do that, I just used that procedure in the OP to demonstrate that the issue is dependent on the `chokidar` line. If that line is enabled, all I have to do is click on the navigation links (Home, About, Blog) and I'll get 404s. I don't have to modify any of the source or content.  (Going from memory there but pretty sure!).

**Comment by theWebalyst** [comment] 2019-02-12 17:08
@tannerlinsley did you have a look at this?

**Comment by oscartbeaumont** [comment] 2019-03-02 05:48
I am also having this issue. If I startup react-static and then just save the `static.config.js` without even making a change to the file, my routes from `src/pages/{filename}.js` return 404.

**Comment by oscartbeaumont** [comment] 2019-03-07 14:40
@tannerlinsley can you have a look at this?

**Comment by tannerlinsley** [comment] 2019-03-07 14:48
Yes I can.

**Comment by Blobson** [comment] 2019-03-30 12:59
Hi! Just wondering if there any progress on the issue? I'd really love to migrate to react-static from gatsby but for now it is a major showstopper for me.

**Comment by tannerlinsley** [comment] 2019-03-30 14:57
This is fixed in v7. We found some architecture  decisions made in v6 that we had to break to fix it. Alpha will be available this afternoon.

Tanner Linsley

**Comment by Blobson** [comment] 2019-03-30 15:38
This is great! Can't wait to try it out.

**Comment by tannerlinsley** [comment] 2019-04-01 17:33
v7 is now available to try at `react-static@next` or `react-static@7`. 

Be sure to use the new `reloadClientData` instead of the deprecated `reloadRoutes` method. Thanks!

**Closed by tannerlinsley** 2019-04-01 17:33 UTC
